# Generated by Django 5.0.7 on 2025-04-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instructor_applied',
            field=models.BooleanField(default=False),
        ),
    ]
