# Generated by Django 5.0.7 on 2025-04-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_instructor_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instructor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
