# Generated by Django 5.0.7 on 2025-04-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='old_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
