# Generated by Django 5.0.7 on 2025-04-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='promo_video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_text',
            field=models.TextField(blank=True, help_text='Detailed course syllabus'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_video',
            field=models.FileField(blank=True, help_text='Upload video file if not using URL', null=True, upload_to='course_videos/'),
        ),
    ]
