# Generated by Django 5.0.7 on 2025-04-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_course_promo_video_url_course_syllabus_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
