# Generated by Django 5.0.7 on 2025-04-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='promo_video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL', max_length=350, null=True),
        ),
    ]
