# Generated by Django 5.0.7 on 2025-03-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobannouncement',
            name='category',
            field=models.CharField(choices=[('software_dev', 'Software Development'), ('data_science', 'Data Science'), ('cybersecurity', 'Cybersecurity'), ('networking', 'Networking & Infrastructure'), ('ai_ml', 'AI & Machine Learning'), ('cloud_computing', 'Cloud Computing'), ('it_support', 'IT Support & Administration'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
